#!/usr/bin/env python3
"""Generate `docs/adr/README.md` from each ADR's frontmatter, and check it is current.

The index is derived, never hand-edited: a list maintained by hand drifts from the
folder beside it within a few entries, and an index that lies is worse than none.
`--check` is the CI half, so a new ADR cannot land without its row.

The frontmatter is read through a pydantic model, so a malformed one fails naming
the file and the field rather than silently producing an index with a hole in it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from pydantic import BaseModel, ConfigDict, Field, ValidationError  # noqa: E402

from meetlat import console  # noqa: E402

ADR_DIR = REPO_ROOT / "docs" / "adr"
INDEX = ADR_DIR / "README.md"

_FRONTMATTER = re.compile(r"\A---\n(?P<body>.*?)\n---\n", re.DOTALL)
_SCALAR = re.compile(r"^(?P<key>[a-z_]+):\s*(?P<value>.*)$")
_HEADING = re.compile(r"^#\s*ADR\s*\d+:\s*(?P<title>.+)$", re.MULTILINE)


class Frontmatter(BaseModel):
    """What every ADR declares about itself."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    status: str = Field(pattern=r"^(accepted|superseded|withdrawn)$")
    area: list[str] = Field(min_length=1)
    date: str = Field(pattern=r"^\d{4}-\d{2}-\d{2}$")
    supersedes: list[int] = []
    amends: list[int] = []
    #: Where the decision landed so it binds at edit time: a rules file, a gate, or
    #: both. An ADR that names neither is a decision nothing enforces (ADR-0006).
    rule: list[str] = []
    enforced_by: list[str] = []


def _parse_list(raw: str) -> list[str]:
    inner = raw.strip().removeprefix("[").removesuffix("]").strip()
    return [item.strip().strip("\"'") for item in inner.split(",") if item.strip()]


def _read(path: Path) -> tuple[Frontmatter, str]:
    text = path.read_text(encoding="utf-8")
    match = _FRONTMATTER.match(text)
    if not match:
        raise ValueError(f"{path.name}: no frontmatter block")
    fields: dict[str, object] = {}
    for line in match.group("body").splitlines():
        if not (scalar := _SCALAR.match(line)):
            continue
        key, value = scalar.group("key"), scalar.group("value").strip()
        fields[key] = _parse_list(value) if value.startswith("[") else value
    heading = _HEADING.search(text)
    if not heading:
        raise ValueError(f"{path.name}: no '# ADR NNNN: Title' heading")
    return Frontmatter.model_validate(fields), heading.group("title").strip()


def render() -> str:
    rows: list[str] = []
    by_area: dict[str, list[str]] = {}
    for path in sorted(ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md")):
        front, title = _read(path)
        number = path.name[:4]
        landing = ", ".join(f"`{x}`" for x in front.rule + front.enforced_by) or "—"
        edges = "".join(
            f" (supersedes {', '.join(f'ADR-{n:04d}' for n in front.supersedes)})"
            if front.supersedes
            else ""
        )
        row = (
            f"| [{number}]({path.name}) | {title}{edges} | {front.status} | "
            f"{front.date} | {landing} |"
        )
        rows.append(row)
        for area in front.area:
            by_area.setdefault(area, []).append(f"[ADR-{number}]({path.name})")

    areas = "\n".join(f"- **{area}**: {', '.join(adrs)}" for area, adrs in sorted(by_area.items()))
    return f"""<!-- Generated by scripts/generate_adr_index.py. Run `make adr-index`. -->
# Decision log

Why the harness is shaped the way it is. These are the historical record: read one
before changing what it governs, and do not read one to learn the current rule. What
is true *now* lives in `AGENTS.md` and in the gates each ADR names below.

| # | Decision | Status | Date | Landed in |
| --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## By area

{areas}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the index is stale")
    args = parser.parse_args(argv)

    try:
        rendered = render()
    except (ValueError, ValidationError) as exc:
        console.err(str(exc))
        return 1

    if not args.check:
        INDEX.write_text(rendered, encoding="utf-8")
        console.ok(f"wrote {INDEX.relative_to(REPO_ROOT)}")
        return 0

    current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
    if current == rendered:
        console.ok("ADR index is current")
        return 0
    console.err("docs/adr/README.md is stale; run `make adr-index` and commit it")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
